AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Functions

Resources:
  addSecurityHeadersFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: add-security-headers
      AutoPublish: true
      FunctionConfig:
        Comment: Adds security headers to the response
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        function handler(event) {
            var response = event.response;
            var headers = response.headers;

            // Set HTTP security headers
            // Since JavaScript doesn't allow for hyphens in variable names, we use the dict["key"] notation
            headers['strict-transport-security'] = { value: 'max-age=63072000; includeSubdomains; preload'};
            headers['content-security-policy'] = { value: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"};
            headers['x-content-type-options'] = { value: 'nosniff'};
            headers['x-frame-options'] = {value: 'DENY'};
            headers['x-xss-protection'] = {value: '1; mode=block'};

            // Return the response to viewers
            return response;
        }

Outputs:
  S3BucketName:
    Description: Add Security Headers CloudFront Function.
    Value: !GetAtt addSecurityHeadersFunction.FunctionARN
    Export:
      Name:
        'Fn::Sub': '${AWS::StackName}-AddSecurityHeadersFunction'
